# Project information
site_name: Topomine &mdash; Documentation
site_url: https://paris-timemachine.huma-num.fr/app/topomine/doc/
site_author: EG/EM (PTM)
site_description: >-
  Topomine est une application web permettant d'explorer et de visualiser
  des données relatives à la toponymie en France. La toponymie est porteuse
  de sens multiples sur le temps long et parfois cachés dans l'évolution
  des langues et dialectes français. Agrégeant plusieurs bases de données
  issues de différents producteurs, Topomine allie une recherche avancée
  par mots-clés qui permet de faire émerger et de révéler des logiques
  spatiales sous-jacentes à certains phénomènes d'études en histoire,
  en géographie, en études environnementales, en littérature, en études
  du genre ou encore en généalogie.

# Repository
# repo_name: paristimemachine/topomine-docs
# repo_url: https://github.com/paristimemachine/topomine-docs

# Copyright
copyright: Paris Time Machine &mdash; 2023

theme:
  name: material
  custom_dir: ./docs/overrides
  language: fr
  logo: assets/images/topomine-logo-original.png

  features:
    - header.autohide
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.footer
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate


#  palette:
#    - scheme: default
#      toggle:
##        icon: material/toggle-switch-off-outline
#        icon: material/weather-sunny
#        name: Passer en mode nuit / Switch to dark mode
#    - scheme: slate
#      toggle:
##        icon: material/toggle-switch
#        icon: material/weather-night
#        name: Passer en mode jour / Switch to light mode

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
#        icon: material/toggle-switch-off-outline
#        icon: material/weather-sunny
        icon: material/brightness-7
        name: Passer en mode nuit / Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
#        icon: material/toggle-switch
#        icon: material/weather-night
        icon: material/brightness-4
        name: Passer en mode jour / Switch to light mode

# extra:
#   alternate:
#     - name: Français
#       link: /
#       lang: fr
#     - name: English
#       link: /en/
#       lang: en
#   version:
#     provider: mike

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - fr
        # - en
#  - with-pdf # doesn't work on Ubuntu 18, work on 20 (requires libpango >= 1.44)
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/paristimemachine
#    - icon: fontawesome/brands/python
#      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TimeParis

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

# Page tree
nav:
  - Home: index.md
  - Contexte: contexte.md
  - Bien démarrer: bien_demarrer.md
  - Requêtes: requetes.md
  # - Cas d'études:
    # - Dossier 1 index: dossier_1/index.md
    # - Toponymie relationnelle: dossier_1/nav1.md
    # - Toponymie littéraire: dossier_1/nav2.md
    # - Toponymie politique: dossier_1/nav3.md
