# Project information
site_name: Topomine &mdash; Documentation
site_url: https://paris-timemachine.huma-num.fr/app/topomine/doc/
site_author: EG/EM (PTM)
site_description: >-
  Documentation de Topomine

theme:
  name: material
  # custom_dir: overrides
  language: fr

  features:
    - header.autohide
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate


#  palette:
#    - scheme: default
#      toggle:
##        icon: material/toggle-switch-off-outline
#        icon: material/weather-sunny
#        name: Passer en mode nuit / Switch to dark mode
#    - scheme: slate
#      toggle:
##        icon: material/toggle-switch
#        icon: material/weather-night
#        name: Passer en mode jour / Switch to light mode

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
#        icon: material/toggle-switch-off-outline
        icon: material/weather-sunny
        name: Passer en mode nuit / Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
#        icon: material/toggle-switch
        icon: material/weather-night
        name: Passer en mode jour / Switch to light mode

# extra:
#   alternate:
#     - name: Français
#       link: /
#       lang: fr
#     - name: English
#       link: /en/
#       lang: en
#   version:
#     provider: mike

plugins:
  - search:
      lang:
        - fr
        # - en
#  - with-pdf # doesn't work on Ubuntu 18, work on 20 (requires libpango >= 1.44)

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
