# Project information
site_name: Topomine &mdash; Documentation
site_url: https://paris-timemachine.huma-num.fr/app/topomine/doc/
site_author: EG/EM (PTM)
site_description: >-
  Description de la documentation de Topomine


# Repository
# repo_name: paristimemachine/topomine-docs
# repo_url: https://github.com/paristimemachine/topomine-docs

# Copyright
copyright: Paris Time Machine &mdash; 2023

theme:
  name: material
  custom_dir: ./docs/overrides
  language: fr
  logo: assets/images/topomine-logo-original.png

  features:
    - header.autohide
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.footer
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate


#  palette:
#    - scheme: default
#      toggle:
##        icon: material/toggle-switch-off-outline
#        icon: material/weather-sunny
#        name: Passer en mode nuit / Switch to dark mode
#    - scheme: slate
#      toggle:
##        icon: material/toggle-switch
#        icon: material/weather-night
#        name: Passer en mode jour / Switch to light mode

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
#        icon: material/toggle-switch-off-outline
#        icon: material/weather-sunny
        icon: material/brightness-7
        name: Passer en mode nuit / Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
#        icon: material/toggle-switch
#        icon: material/weather-night
        icon: material/brightness-4
        name: Passer en mode jour / Switch to light mode

# extra:
#   alternate:
#     - name: Français
#       link: /
#       lang: fr
#     - name: English
#       link: /en/
#       lang: en
#   version:
#     provider: mike

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - fr
        # - en
#  - with-pdf # doesn't work on Ubuntu 18, work on 20 (requires libpango >= 1.44)
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/paristimemachine
#    - icon: fontawesome/brands/python
#      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TimeParis

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  
# Page tree
nav:
  - Home: index.md
  - Quick start: quick_start.md
  - Dossier 0:
    - Dossier 0 index: dossier_0/index.md
  - Dossier 1:
    # - Dossier 1 index: dossier_1/index.md
    - Nav 1: dossier_1/nav1.md
    - Nav 2: dossier_1/nav2.md
    - Nav 3: dossier_1/nav3.md
