# Project information
site_name: Topomine &mdash; Documentation
site_url: https://doc.ptm.huma-num.fr/topomine/
site_author: EG/EM (PTM)
site_description: >-
  Topomine est une application web permettant d'explorer et de visualiser
  des données relatives à la toponymie en France. La toponymie est porteuse
  de sens multiples sur le temps long et parfois cachés dans l'évolution
  des langues et dialectes français. Agrégeant plusieurs bases de données
  issues de différents producteurs, Topomine allie une recherche avancée
  par mots-clés qui permet de faire émerger et de révéler des logiques
  spatiales sous-jacentes à certains phénomènes d'études en histoire,
  en géographie, en études environnementales, en littérature, en études
  du genre ou encore en généalogie.

# Repository
repo_name: paristimemachine/topomine-documentation
repo_url: https://github.com/paristimemachine/topomine-documentation

# Copyright
copyright: <a href="https://ptm.huma-num.fr/" target="_blank">PTM</a> &mdash; 2023-2025

theme:
  name: material
  custom_dir: ./docs/overrides
  language: fr
  logo: assets/images/topomine-logo-original.png
  favicon: assets/images/topomine-favicon.png

  features:
    # - header.autohide
    # - content.tabs.link
    # - navigation.expand
    - navigation.indexes
    - navigation.footer
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb # material/brightness-7 material/toggle-switch-off-outline / material/weather-sunny
        name: Passer en mode nuit # Passer en mode nuit / Switch to dark mode
        
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/lightbulb-outline # material/brightness-4 material/toggle-switch / material/weather-night
        name: Passer en mode jour # name: Passer en mode jour / Switch to light mode

# extra:
#   alternate:
#     - name: Français
#       link: /
#       lang: fr
#     - name: English
#       link: /en/
#       lang: en
#   version:
#     provider: mike

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - fr
        # - en
  - with-pdf: # Ubuntu 20+ as it requires libpango >= 1.44
      author: Eric Mermet et Eric Grosso (PTM)
      # copyright: ANY TEXT
      
      cover: true
      # back_cover: true
      cover_logo: assets/images/topomine-logo-original.png
      cover_title: Documentation
      cover_subtitle: Français
      # custom_template_path: TEMPLATES PATH
      
      toc_title: Topomine
      # heading_shift: false
      # toc_level: 3
      # ordered_chapter_level: 2
      # excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      
      # exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      # convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      # two_columns_level: 3
      
      # render_js: true
      # headless_chrome_path: headless-chromium

      output_path: /tmp/Topomine-documentation.pdf
      enabled_if_env: ENABLE_PDF_EXPORT

      # debug_html: true
      # show_anchors: true
      # verbose: true

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/paristimemachine
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/ptm-huma-num.bsky.social
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/TimeParis

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - footnotes

# Page tree
nav:
  - Accueil: index.md
  - Présentation: presentation.md
  - Bien démarrer: bien_demarrer.md
  - Requêtes: requetes.md
  # - Cas d'études:
    # - Dossier 1 index: dossier_1/index.md
    # - Toponymie relationnelle: dossier_1/nav1.md
    # - Toponymie littéraire: dossier_1/nav2.md
    # - Toponymie politique: dossier_1/nav3.md
